---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eth-demo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/eth-demo
    type: ""
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eth-demo-pvc
spec:
  storageClassName: standard
  volumeName: eth-demo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: geth-demo
spec:
  replicas: 1
  serviceName: geth-demo-service
  selector:
    matchLabels:
      app: geth-demo
  template:
    metadata:
      labels:
        app: geth-demo
    spec:
      containers:
        - name: geth-demo
          imagePullPolicy: Never
          image: ethereum/restrike
          #            args:
          #              [
          #                "--http",
          #                "--http.addr=0.0.0.0",
          #                "--http.vhosts=geth-mainnet-full",
          #                "--http.api=eth,net,web3,txpool",
          #                "--ws",
          #                "--ws.addr=0.0.0.0",
          #                "--datadir=/data",
          #              ]
          env:
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 2Gi
          ports:
            - containerPort: 8545
              name: gethrpc
            - containerPort: 30303
              name: gethdiscovery
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: eth-demo-pvc
