apiVersion: v1
kind: Service
metadata:
  name: geth-demo-service
spec:
  type: LoadBalancer
  selector:
    app: geth-demo
  ports:
    - protocol: TCP
      name: jsonrpc
      port: 8545
      targetPort: 8545
    - protocol: TCP
      name: listener
      port: 30303
      targetPort: 30303
    - protocol: UDP
      name: discovery
      port: 30303
      targetPort: 30303
